/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub.frontend;

import connecthub.ContentFactory;
import connecthub.Post;
import connecthub.ReadWrite;
import connecthub.ReadWriteStory;
import connecthub.Story;
import connecthub.postStoryManagment;
import java.awt.Image;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class AddStoryFrame extends javax.swing.JFrame {
   postStoryManagment pst=new postStoryManagment();

    /**
     * Creates new form AddStoryFrame
     */
    public AddStoryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jimage = new javax.swing.JLabel();
        Sharebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Sharebutton.setText("Share");
        Sharebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SharebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Sharebutton)))
                .addGap(55, 55, 55)
                .addComponent(jimage, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(Sharebutton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jimage, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SharebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SharebuttonActionPerformed
        // TODO add your handling code here:
        ContentFactory F= new ContentFactory();
        Story s = (Story) F.createpoststory("story");
        //User user= UserDatabase.getCurrentuser();
        String content = jTextArea1.getText();
        if (content == null || content.trim().isEmpty()) {
     if (content == null || content.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Content cannot be empty" , "Error", JOptionPane.ERROR_MESSAGE);
            return;
            
        }
    
}
        // if(user==null)
        //{JOptionPane.showMessageDialog(this, "No user is Currently Loggedin ", "Error", JOptionPane.ERROR_MESSAGE);}

        String imagePath=null;
       
        int result =JOptionPane.showConfirmDialog(this, "Do You want to add a photo to this post ?","Add Photo",JOptionPane.YES_NO_OPTION);
       if(result==JOptionPane.YES_OPTION){
         JFileChooser filechooser=new JFileChooser();
            filechooser.setDialogTitle(imagePath);
            filechooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files","jpg","png","jpeg"));
            int fileResult=filechooser.showOpenDialog(this);
            if(fileResult==JFileChooser.APPROVE_OPTION){
                imagePath=filechooser.getSelectedFile().getAbsolutePath();
                ImageIcon imageIcon = new ImageIcon(imagePath);
                Image img = imageIcon.getImage();
            Image scaledImg = img.getScaledInstance(jimage.getWidth(), jimage.getHeight(), Image.SCALE_AREA_AVERAGING);
            imageIcon = new ImageIcon(scaledImg);
                jimage.setIcon(imageIcon);
            

        }}

        s.setContent(content);
        s.setTimeStamp(LocalDateTime.now());
        // p.setAuthorid(user.getUserId());
        s.setContentid(UUID.randomUUID().toString());
        if(imagePath!=null)
        {s.setimage(imagePath);}
        JOptionPane.showMessageDialog(this, "Story shared successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        pst.addStory(s);

        
        
    }//GEN-LAST:event_SharebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sharebutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jimage;
    // End of variables declaration//GEN-END:variables
}
