/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import java.io.IOException;
import java.util.UUID;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Raz_RAMADAN
 */
public class AddGroupPost extends javax.swing.JFrame {

    NewsFeed n;
    GroupManagment gm = new GroupManagment();
    private String groupid;
    private String postid;

    /**
     * Creates new form AddGroupPost
     */
    public AddGroupPost(NewsFeed n, String groupid) {
        initComponents();
        this.n = n;
        this.groupid = groupid;
    }

    public void addpost() {
        try {
            String text = postarea.getText();
            //groupposts.add(GC.newpost(postid, Groupid,postcontent,imagepath));
            String imagePath = null;
            int result = JOptionPane.showConfirmDialog(this, "Do You want to add a photo  ?", "Add Photo", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                JFileChooser filechooser = new JFileChooser();
                filechooser.setDialogTitle(imagePath);
                filechooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
                int fileResult = filechooser.showOpenDialog(this);
                if (fileResult == JFileChooser.APPROVE_OPTION) {
                    imagePath = filechooser.getSelectedFile().getAbsolutePath();

                }
            }
            postid = UUID.randomUUID().toString();
            gm.addnewpost(postid, groupid, postarea.getText(), imagePath);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Process Failed " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        postarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DoneButton.setBackground(new java.awt.Color(153, 153, 153));
        DoneButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        postarea.setColumns(20);
        postarea.setRows(5);
        jScrollPane1.setViewportView(postarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:

        addpost();

        

        this.setVisible(false);
        n.setVisible(true);

    }//GEN-LAST:event_DoneButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea postarea;
    // End of variables declaration//GEN-END:variables
}
