/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import static connecthub.UserDatabase.getCurrentuser;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author janaf
 */
public class Friends extends javax.swing.JFrame {
    FriendsManagment fdb=FriendsManagment.getInstance();
    UserDatabase udb=UserDatabase.getInstance();
    User me=getCurrentuser();
    HashMap<Integer, String> map=new HashMap<>();
    NewsFeed n;
    /**
     * Creates new form Friends
     */
    public Friends(NewsFeed n) {
        initComponents();
        this.n=n;
        showRequests();
    }
    public void showRequests(){
        ArrayList<String> friendsUserIDs=fdb.getFriendRequestsof(me.getUserId());
        ArrayList<String> friendsUsernames=new ArrayList<>();
        int i=0;
        for(String id:friendsUserIDs){
            User u=udb.getUserById(id);
            friendsUsernames.add(u.getUsername());
            map.put(i, id);
            i++;
        }
        String []arr1=new String[friendsUsernames.size()];
        String[]arr2=friendsUsernames.toArray(arr1);
        requests.setListData(arr2);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suggestionsB = new javax.swing.JButton();
        yourFriendsB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requests = new javax.swing.JList<>();
        acceptButton = new javax.swing.JButton();
        declineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Friends");

        suggestionsB.setText("Suggestions");
        suggestionsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionsBActionPerformed(evt);
            }
        });

        yourFriendsB.setText("Your Friends");
        yourFriendsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourFriendsBActionPerformed(evt);
            }
        });

        jLabel1.setText("Friend Requests (Pending)");

        jScrollPane1.setViewportView(requests);

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        declineButton.setText("Decline");
        declineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(suggestionsB)
                        .addGap(74, 74, 74)
                        .addComponent(yourFriendsB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acceptButton)
                            .addGap(47, 47, 47)
                            .addComponent(declineButton))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestionsB)
                    .addComponent(yourFriendsB))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptButton)
                    .addComponent(declineButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suggestionsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionsBActionPerformed
        Suggestions s=new Suggestions(this);
        s.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_suggestionsBActionPerformed

    private void yourFriendsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourFriendsBActionPerformed
        MyFriends mf=new MyFriends(this);
        mf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_yourFriendsBActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        int i=requests.getSelectedIndex();
        String id=map.get(i);
        fdb.AcceptRrquest(me.getUserId(),id);
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void declineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButtonActionPerformed
        int i=requests.getSelectedIndex();
        String id=map.get(i);
        fdb.DeclineRequest(me.getUserId(),id);
    }//GEN-LAST:event_declineButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton declineButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> requests;
    private javax.swing.JButton suggestionsB;
    private javax.swing.JButton yourFriendsB;
    // End of variables declaration//GEN-END:variables
}
