/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author hp
 */
public class GroupFrame extends javax.swing.JFrame {

    JSONArray arr;
    NewsFeed n;

    /**
     * Creates new form GroupFrame
     */
    public GroupFrame(NewsFeed n, JSONArray arr) {
        initComponents();
        this.n = n;
        this.arr = arr;
        setSize(400, 400);
        displayPosts();
    }

    private void displayPosts() {

        for (int j = 0; j < arr.length(); j++) {
            JSONObject post = arr.getJSONObject(j);

            // Create a new label for the post
            JLabel postLabel = new JLabel();
            postLabel.setText(post.getString("postcontent"));
            if (post.has("imagepath")) {
                ImageIcon originalIcon = new ImageIcon(post.getString("imagepath"));
                Image originalImage = originalIcon.getImage();
                Image resizedImage = originalImage.getScaledInstance(150, 200, Image.SCALE_SMOOTH);
                ImageIcon resizedIcon = new ImageIcon(resizedImage);
                postLabel.setIcon(resizedIcon); // Add resized image }
            }

            postspanel.add(postLabel); // Add label to the panel
        }

        postspanel.setLayout(new BoxLayout(postspanel, BoxLayout.Y_AXIS));
        postspanel.revalidate();
        postspanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        postspanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        postspanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout postspanelLayout = new javax.swing.GroupLayout(postspanel);
        postspanel.setLayout(postspanelLayout);
        postspanelLayout.setHorizontalGroup(
            postspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        postspanelLayout.setVerticalGroup(
            postspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(postspanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel postspanel;
    // End of variables declaration//GEN-END:variables
}
