/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class groupmanagmentframe extends javax.swing.JFrame {
    GroupManagment gm=new GroupManagment();
     
     GroupProfile n;

    /**
     * Creates new form groupmanagmentframe
     */
    public groupmanagmentframe(GroupProfile n) {
        initComponents();
        this.n=n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddAdminButton = new javax.swing.JButton();
        AddMemberButton = new javax.swing.JButton();
        RemoveMemberButton = new javax.swing.JButton();
        RemoveAdminButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddAdminButton.setText("Add Admin");
        AddAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminButtonActionPerformed(evt);
            }
        });

        AddMemberButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddMemberButton.setText("Add Member");
        AddMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMemberButtonActionPerformed(evt);
            }
        });

        RemoveMemberButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveMemberButton.setText("Remove Member");
        RemoveMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMemberButtonActionPerformed(evt);
            }
        });

        RemoveAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveAdminButton.setText("RemoveAdmin");
        RemoveAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAdminButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Add Post");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Edit Post");

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Delete Post");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMemberButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveMemberButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminButtonActionPerformed
        // TODO add your handling code here:
        String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");
        
        if(gm.istheprimaryadmin(userid,groupid))
        { addadminframe a=new addadminframe(n,groupid);
        a.setVisible(true);
        this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not the primary admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
        
        
    }//GEN-LAST:event_AddAdminButtonActionPerformed

    private void RemoveAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAdminButtonActionPerformed
        // TODO add your handling code here:
         String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");
        
        if(gm.istheprimaryadmin(userid,groupid)||gm.isanadmin(userid, groupid))
        { removeadmFrame a=new removeadmFrame(this,groupid);
        a.setVisible(true);
        this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not an primary admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
        
    }//GEN-LAST:event_RemoveAdminButtonActionPerformed

    private void AddMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberButtonActionPerformed
        // TODO add your handling code here:
        String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");
        
        if(gm.istheprimaryadmin(userid,groupid)||gm.isanadmin(userid, groupid))
        { addmemberframe a=new addmemberframe(this,groupid);
        a.setVisible(true);
        this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not an admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
        
        
    }//GEN-LAST:event_AddMemberButtonActionPerformed

    private void RemoveMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMemberButtonActionPerformed
        // TODO add your handling code here:
         String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");
        
        if(gm.istheprimaryadmin(userid,groupid)||gm.isanadmin(userid, groupid))
        { removeMemFrame r=new removeMemFrame(this,groupid);
        r.setVisible(true);
        this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not an admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
        
        
    }//GEN-LAST:event_RemoveMemberButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");
        
        if(gm.istheprimaryadmin(userid,groupid)||gm.isanadmin(userid, groupid)||gm.ismember(userid, groupid))
        { 
        AddGroupPost a =new AddGroupPost(n,groupid,userid);
        a.setVisible(true);
        this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not an admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       /* String userid=JOptionPane.showInputDialog(this,"Please Enter Your id");
        String groupid=JOptionPane.showInputDialog(this,"Please Enter groupid");

        if(gm.istheprimaryadmin(userid,groupid)||gm.isanadmin(userid, groupid)||gm.ismember(userid, groupid))
        {
            RemoveGroupPost a =new RemoveGroupPost(n,groupid);
            a.setVisible(true);
            this.setVisible(false);}
        else{JOptionPane.showMessageDialog(this, "Sorry, you are not an admin" ,"Message", JOptionPane.INFORMATION_MESSAGE);}
*/
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdminButton;
    private javax.swing.JButton AddMemberButton;
    private javax.swing.JButton RemoveAdminButton;
    private javax.swing.JButton RemoveMemberButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
