/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import static connecthub.UserDatabase.getCurrentuser;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;

/**
 *
 * @author janaf
 */

public class MyFriends extends javax.swing.JFrame {
    Friends f;
    User me=getCurrentuser();
    FriendsManagment fdb=FriendsManagment.getInstance();
    UserDatabase udb=UserDatabase.getInstance();
    HashMap<Integer, String> map=new HashMap<>();
    /**
     * Creates new form MyFriends
     */
    public MyFriends(Friends f) {
        initComponents();
        this.f=f;
        showFriends();
    }
    public void showFriends(){
        ArrayList<String> friendsUserIDs=fdb.getFriendsof(me.getUserId());
        ArrayList<String> friendsUsernames=new ArrayList<>();
        int i=0;
        for(String id:friendsUserIDs){
            User u=udb.getUserById(id);
            friendsUsernames.add(u.getUsername());
            map.put(i, id);
            i++;
        }
        String []arr1=new String[friendsUsernames.size()];
        String[]arr2=friendsUsernames.toArray(arr1);
        MyFriendsList.setListData(arr2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelfriends = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyFriendsList = new javax.swing.JList<>();
        blockbutton = new javax.swing.JButton();
        removebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        labelfriends.setText("Your friends");

        jScrollPane1.setViewportView(MyFriendsList);

        blockbutton.setText("Block");
        blockbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockbuttonActionPerformed(evt);
            }
        });

        removebutton.setText("Remove");
        removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelfriends, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(blockbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removebutton)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelfriends, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockbutton)
                    .addComponent(removebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blockbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockbuttonActionPerformed
        if(MyFriendsList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "you need to select", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int i=MyFriendsList.getSelectedIndex();
        String id=map.get(i);
        fdb.Block(me.getUserId(),id);
        JOptionPane.showMessageDialog(this, "Blocked", "message", PLAIN_MESSAGE);
        showFriends();
    }//GEN-LAST:event_blockbuttonActionPerformed

    private void removebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebuttonActionPerformed
        if(MyFriendsList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "you need to select", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int i=MyFriendsList.getSelectedIndex();
        String id=map.get(i);
        fdb.Remove(me.getUserId(),id);
        JOptionPane.showMessageDialog(this, "Removed", "message", PLAIN_MESSAGE);
        showFriends();
    }//GEN-LAST:event_removebuttonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MyFriendsList;
    private javax.swing.JButton blockbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfriends;
    private javax.swing.JButton removebutton;
    // End of variables declaration//GEN-END:variables
}
