/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import java.util.ArrayList;

/**
 *
 * @author janaf
 */
public class MyFriends extends javax.swing.JFrame {
    User me;
    FriendsDatabase fdb;
    UserDatabase udb;
    /**
     * Creates new form MyFriends
     */
    public MyFriends(User me,FriendsDatabase fdb,UserDatabase udb) {
        initComponents();
        this.me=me;
        this.fdb=fdb;
        this.udb=udb;
    }
    public void showRequests(){
        ArrayList<String> friendsUserIDs=fdb.getFriendsof(me.getUserId());
        ArrayList<String> friendsUsernames=new ArrayList<>();
        for(String id:friendsUserIDs){
            User u=udb.getUserById(id);
            friendsUsernames.add(u.getUsername());
        }
        String []arr1=new String[friendsUsernames.size()];
        String[]arr2=friendsUsernames.toArray(arr1);
        MyFriendsList.setListData(arr2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelfriends = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyFriendsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelfriends.setText("Your friends");

        jScrollPane1.setViewportView(MyFriendsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelfriends, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelfriends, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MyFriendsList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfriends;
    // End of variables declaration//GEN-END:variables
}
