/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;
import connecthub.UserDatabase;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
/**
 *
 * @author Raz_RAMADAN
 */
public class NewsFeed extends javax.swing.JFrame {
            public static NewsFeed fn=null;
            

private UserDatabase database=UserDatabase.getInstance();
private User user=UserDatabase.getCurrentuser();
private ProfileManagement profile;
    FriendsManagment fdb=FriendsManagment.getInstance();
    UserDatabase udb=UserDatabase.getInstance();
    postStoryManagment psm=new postStoryManagment();
    NewsfeedService nf=new NewsfeedService();

    /**
     * Creates new form NewsFeed
     */
    private NewsFeed() {
        initComponents();
        this.database=database;
        this.user=user;
        profile=new ProfileManagement();
        System.out.println(user);
        showFriends();
        showSuggest();
    }
    public static NewsFeed getInstance(){
        if(fn==null){
            fn=new NewsFeed();
        }
        return fn;
    }

    public void showFriends(){
        ArrayList<String> friendsUserIDs=fdb.getFriendsof(user.getUserId());
        ArrayList<String> friendsUsernames=new ArrayList<>();
        int i=0;
        for(String id:friendsUserIDs){
            User u=udb.getUserById(id);
            friendsUsernames.add(u.getUsername());
        }
        String []arr1=new String[friendsUsernames.size()];
        String[]arr2=friendsUsernames.toArray(arr1);
        MyFriendsList.setListData(arr2);
    }
    public void showSuggest(){
        ArrayList<String> friendsUserIDs=fdb.getSuggestedTo(user.getUserId());
        ArrayList<String> friendsUsernames=new ArrayList<>();
        for(String id:friendsUserIDs){
            User u=udb.getUserById(id);
            friendsUsernames.add(u.getUsername());
        }
        String []arr1=new String[friendsUsernames.size()];
        String[]arr2=friendsUsernames.toArray(arr1);
        suggList.setListData(arr2);
    }
    public void showStories() {
    // Fetch stories from the NewsfeedService
    ArrayList<Story> stories = (ArrayList<Story>) nf.getfriendsStories();

    // Use a DefaultListModel to populate the list
    DefaultListModel<Story> storyListModel = new DefaultListModel<>();
    for (Story story : stories) {
        storyListModel.addElement(story);
    }

    // Ensure jstories is a JList<Story> and set the model
    JList<Story> storyList = new JList<>(storyListModel);

    // Set a custom cell renderer to display images and text
    storyList.setCellRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Story) {
                Story story = (Story) value;

                // Load and scale the image
                ImageIcon icon = new ImageIcon(story.getImagepath());
                Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); // Adjust size as needed
                icon = new ImageIcon(img);

                // Set the label with the image and story content
                label.setIcon(icon);
                label.setText(story.getContent());
                label.setHorizontalTextPosition(JLabel.RIGHT);
            }
            return label;
        }
    });

    // Add the story list to a scroll pane for display
    jScrollPane3.setViewportView(storyList);
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        friendspage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyFriendsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        suggList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jstories = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jposts = new javax.swing.JList<>();
        addpost = new javax.swing.JButton();
        addstory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NewsFeed Frame");

        LogOutButton.setBackground(new java.awt.Color(204, 204, 255));
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("NewsFeed Page");
        jLabel1.setOpaque(true);

        jButton1.setText("My Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        friendspage.setText("Friends");
        friendspage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendspageActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(MyFriendsList);

        jScrollPane2.setViewportView(suggList);

        jScrollPane3.setViewportView(jstories);

        jScrollPane4.setViewportView(jposts);

        addpost.setText("Add Post");
        addpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpostActionPerformed(evt);
            }
        });

        addstory.setText("Add Story");
        addstory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addpost)
                        .addGap(18, 18, 18)
                        .addComponent(addstory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23)
                        .addComponent(friendspage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LogOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOutButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(friendspage)
                    .addComponent(addpost)
                    .addComponent(addstory))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        database.logout(user.getEmail());
        MainWindow frame=MainWindow.getInstance();
                frame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /*profileframe frame = new profileframe(database,user,profile,this);
        frame.setVisible(true);
                this.dispose();*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void friendspageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendspageActionPerformed
        Friends f=new Friends(this);
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_friendspageActionPerformed

    private void addpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpostActionPerformed
        AddPost a=new AddPost();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addpostActionPerformed

    private void addstoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstoryActionPerformed
        AddStoryFrame a=new AddStoryFrame();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addstoryActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JList<String> MyFriendsList;
    private javax.swing.JButton addpost;
    private javax.swing.JButton addstory;
    private javax.swing.JButton friendspage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> jposts;
    private javax.swing.JList<String> jstories;
    private javax.swing.JList<String> suggList;
    // End of variables declaration//GEN-END:variables
}
