/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Raz_RAMADAN
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
   
    public Profile() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpAvater1 = new connecthub.cpAvater();
        ppAvatar1 = new connecthub.ppAvatar();
        camButton2 = new javax.swing.JButton();
        camButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cpAvater1.setImage(new javax.swing.ImageIcon("C:\\pics & videos\\Camera A Ramadan\\IMG_20160207_163913.jpg")); // NOI18N

        ppAvatar1.setImage(new javax.swing.ImageIcon("C:\\omar\\omar.jpg")); // NOI18N
        cpAvater1.add(ppAvatar1);
        ppAvatar1.setBounds(10, 70, 140, 130);

        camButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raz_RAMADAN\\Downloads\\camera.png")); // NOI18N
        camButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camButton2ActionPerformed(evt);
            }
        });
        cpAvater1.add(camButton2);
        camButton2.setBounds(530, 150, 30, 31);

        camButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raz_RAMADAN\\Downloads\\camera.png")); // NOI18N
        camButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camButton1ActionPerformed(evt);
            }
        });
        cpAvater1.add(camButton1);
        camButton1.setBounds(140, 150, 30, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cpAvater1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cpAvater1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose a Profile Photo");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        int result = fileChooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            
            File chosenFile = fileChooser.getSelectedFile();
            String imagePath = chosenFile.getAbsolutePath();
            System.out.println(imagePath);
        //    updateProfile.updateProfileImage(imagePath);
            this.ppAvatar1.setImage(new ImageIcon(imagePath));
            this.ppAvatar1.repaint();
            
        }
    }//GEN-LAST:event_camButton1ActionPerformed

    private void camButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose a cover Photo");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        int result = fileChooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File chosenFile = fileChooser.getSelectedFile();
            String imagePath = chosenFile.getAbsolutePath();
       //     updateProfile.updateCoverimage(imagePath);
            this.cpAvater1.setImage(new ImageIcon(imagePath));
            this.cpAvater1.repaint();
            
        }
    }//GEN-LAST:event_camButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton camButton1;
    private javax.swing.JButton camButton2;
    private connecthub.cpAvater cpAvater1;
    private connecthub.ppAvatar ppAvatar1;
    // End of variables declaration//GEN-END:variables
}
